Repository input-output-hk/catalyst-libs, pull requests merged in 2024-11, with the labels that each got.

#74 feat(general): Bump earthly cat-ci versions
  Earthfile
  docs/Earthfile
  rust/Earthfile
  rust/c509-certificate/Earthfile
  rust/cbork/Earthfile
  rust/deny.toml
Labels: review me

#81 feat(rust/vote-tx-v2): Feat add initial CBOR decoding/encoding implementation of the generalised vote tx
  .github/workflows/semantic_pull_request.yml
  docs/src/architecture/08_concepts/catalyst_voting/cddl/gen_vote_tx.cddl
  docs/src/architecture/08_concepts/catalyst_voting/gen_vote_tx.md
  rust/Cargo.toml
  rust/Earthfile
  rust/vote-tx-v1/Cargo.toml
  rust/vote-tx-v1/src/decoding.rs
  rust/vote-tx-v1/src/lib.rs
  rust/vote-tx-v1/src/utils.rs
  rust/vote-tx-v2/Cargo.toml
  rust/vote-tx-v2/src/decoding.rs
  rust/vote-tx-v2/src/lib.rs
Labels: review me

#82 feat(rust): Move `proptest` to `dev-dependencies`, cleanup prop tests
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/crypto/ed25519/mod.rs
  rust/catalyst-voting/src/crypto/elgamal/mod.rs
  rust/catalyst-voting/src/crypto/group/ristretto255/mod.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/randomness_announcements.rs
  rust/catalyst-voting/src/vote_protocol/committee/mod.rs
  rust/catalyst-voting/src/vote_protocol/voter/mod.rs
  rust/catalyst-voting/src/vote_protocol/voter/proof.rs
  rust/vote-tx-v1/Cargo.toml
  rust/vote-tx-v1/src/decoding.rs
  rust/vote-tx-v1/src/lib.rs
  rust/vote-tx-v2/Cargo.toml
  rust/vote-tx-v2/src/decoding.rs
  rust/vote-tx-v2/src/lib.rs
Labels: review me

#67 feat(rust/immutable-ledger): block encoding decoding and validation
  .github/workflows/semantic_pull_request.yml
  Earthfile
  docs/Earthfile
  rust/Cargo.toml
  rust/Earthfile
  rust/c509-certificate/Earthfile
  rust/cbork/Earthfile
  rust/immutable-ledger/Cargo.toml
  rust/immutable-ledger/src/lib.rs
  rust/immutable-ledger/src/serialize.rs
Labels: review me

#83 feat(rust/vote-tx-v2): Finish `GeneralisedTx` CBOR decoding functionality
  rust/vote-tx-v1/src/decoding.rs
  rust/vote-tx-v2/Cargo.toml
  rust/vote-tx-v2/src/decoding.rs
  rust/vote-tx-v2/src/lib.rs
Labels: review me

#80 feat(rust/cbork): Add a CDDL preprocessing step
  rust/cbork-cddl-parser/Cargo.toml
  rust/cbork-cddl-parser/src/grammar/cddl_test.pest
  rust/cbork-cddl-parser/src/grammar/rfc_8610.pest
  rust/cbork-cddl-parser/src/lib.rs
  rust/cbork-cddl-parser/src/parser.rs
  rust/cbork-cddl-parser/src/preprocessor.rs
  rust/cbork-cddl-parser/tests/byte_sequences.rs
  rust/cbork-cddl-parser/tests/cddl.rs
  rust/cbork-cddl-parser/tests/character_sets.rs
  rust/cbork-cddl-parser/tests/comments.rs
  rust/cbork-cddl-parser/tests/common/mod.rs
  rust/cbork-cddl-parser/tests/group_elements.rs
  rust/cbork-cddl-parser/tests/identifiers.rs
  rust/cbork-cddl-parser/tests/literal_values.rs
  rust/cbork-cddl-parser/tests/rules.rs
  rust/cbork-cddl-parser/tests/text_sequences.rs
  rust/cbork-cddl-parser/tests/type_declarations.rs
Labels: review me

#91 feat(rust/cardano-chain-follower): Implement `time_to_slot` function for `Network`
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/src/network.rs
Labels: enhancement, review me

#90 feat(rust/rbac-registration): add cardano registration chain
  rust/rbac-registration/src/lib.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/payment_history.rs
  rust/rbac-registration/src/registration/cardano/point_tx_idx.rs
  rust/rbac-registration/src/registration/cardano/role_data.rs
  rust/rbac-registration/src/registration/mod.rs
Labels: enhancement
