Repository input-output-hk/catalyst-libs, pull requests merged in 2024-12, with the labels that each got.

#93 fix(rust/rbac-registration): Tracking payment key type
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/role_data.rs
  rust/rbac-registration/src/test_data/cardano/conway_4.block
Labels: bug, enhancement, review me

#85 feat(rust/rbac-registration): RBAC registration
  .github/workflows/semantic_pull_request.yml
  rust/Cargo.toml
  rust/Earthfile
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs.rs
  rust/rbac-registration/src/cardano/cip509/rbac/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/pub_key.rs
  rust/rbac-registration/src/cardano/cip509/rbac/role_data.rs
  rust/rbac-registration/src/cardano/cip509/rbac/tag.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip19.rs
  rust/rbac-registration/src/cardano/cip509/utils/mod.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/cardano/cip509/x509_chunks.rs
  rust/rbac-registration/src/cardano/mod.rs
  rust/rbac-registration/src/cardano/transaction/mod.rs
  rust/rbac-registration/src/cardano/transaction/raw_aux_data.rs
  rust/rbac-registration/src/cardano/transaction/witness.rs
  rust/rbac-registration/src/lib.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/payment_history.rs
  rust/rbac-registration/src/registration/cardano/point_tx_idx.rs
  rust/rbac-registration/src/registration/cardano/role_data.rs
  rust/rbac-registration/src/registration/mod.rs
  rust/rbac-registration/src/test_data/cardano/conway_1.block
  rust/rbac-registration/src/test_data/cardano/conway_2.block
  rust/rbac-registration/src/test_data/cardano/conway_3.block
  rust/rbac-registration/src/test_data/cardano/conway_4.block
  rust/rbac-registration/src/utils/decode_helper.rs
  rust/rbac-registration/src/utils/general.rs
  rust/rbac-registration/src/utils/hashing.rs
  rust/rbac-registration/src/utils/mod.rs
Labels: enhancement, do not merge yet

#95 fix(rust/rbac-registration): Record CIP509 validation data
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/utils/general.rs
Labels: enhancement

#97 fix(rust/rbac-registration): extract type in CIP509 to its own file and implement conversion
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs.rs
  rust/rbac-registration/src/cardano/cip509/rbac/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/pub_key.rs
  rust/rbac-registration/src/cardano/cip509/types/cert_key_hash.rs
  rust/rbac-registration/src/cardano/cip509/types/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/tx_input_hash.rs
  rust/rbac-registration/src/cardano/cip509/utils/mod.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/role_data.rs
Labels: enhancement

#96 fix(rust/cardano-chain-follower): Use CIP509 from `rbac-registration`
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/examples/follow_chains.rs
  rust/cardano-chain-follower/src/metadata/cip509.rs
  rust/cardano-chain-follower/src/metadata/cip509/decode_helper.rs
  rust/cardano-chain-follower/src/metadata/cip509/mod.rs
  rust/cardano-chain-follower/src/metadata/cip509/rbac/certs.rs
  rust/cardano-chain-follower/src/metadata/cip509/rbac/mod.rs
  rust/cardano-chain-follower/src/metadata/cip509/rbac/pub_key.rs
  rust/cardano-chain-follower/src/metadata/cip509/rbac/role_data.rs
  rust/cardano-chain-follower/src/metadata/cip509/utils.rs
  rust/cardano-chain-follower/src/metadata/cip509/x509_chunks.rs
  rust/cardano-chain-follower/src/metadata/mod.rs
  rust/cardano-chain-follower/src/utils.rs
Labels: enhancement

#98 feat(rust/signed-doc): Reference implementation of the Catalyst signed documents with the design doc
  .config/dictionaries/project.dic
  .github/workflows/semantic_pull_request.yml
  rust/Cargo.toml
  rust/Earthfile
  rust/c509-certificate/src/signing.rs
  rust/signed_doc/Cargo.toml
  rust/signed_doc/README.md
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/meta.schema.json
  rust/signed_doc/src/lib.rs
  rust/vote-tx-v2/src/gen_tx/mod.rs
  rust/vote-tx-v2/src/lib.rs
Labels: review me

#110 fix(rust/cardano-chain-follower): Update mithril-client version (0.8.18 -> 0.10.4)
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
Labels: review me

#114 test(general): make allure reports run after ci
  .github/workflows/ci.yml
  .github/workflows/generate-allure-report.yml
Labels: review me

#117 feat(rust/immutable-ledger): Replace `ULID` to `UUID` v7 for `immutable-ledger`
  docs/src/architecture/08_concepts/immutable_ledger/cddl/block.cddl
  docs/src/architecture/08_concepts/immutable_ledger/cddl/genesis_to_prev_hash.cddl
  rust/Earthfile
  rust/immutable-ledger/Cargo.toml
  rust/immutable-ledger/src/serialize.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134.rs
Labels: review me

#116 feat(docs): Add documentation for signed document metadata
  .config/dictionaries/project.dic
  docs/src/architecture/08_concepts/signed_document_metadata/.pages
  docs/src/architecture/08_concepts/signed_document_metadata/metadata.md
Labels: enhancement, review me

#119 feat(rust/rbac-registration): Introduce Cip0134UriSet type
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/tx_input_hash.rs
  rust/rbac-registration/src/cardano/cip509/types/validation_signature.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134/mod.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134/uri.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134/uri_set.rs
  rust/rbac-registration/src/cardano/cip509/utils/mod.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/cardano/cip509/x509_chunks.rs
  rust/rbac-registration/src/lib.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
Labels: review me

#125 feat(rust/cardano-blockchain-types): Add CIP36
  rust/cardano-blockchain-types/src/cip36/key_registration.rs
  rust/cardano-blockchain-types/src/cip36/mod.rs
  rust/cardano-blockchain-types/src/cip36/registration_witness.rs
  rust/cardano-blockchain-types/src/cip36/validation.rs
  rust/cardano-blockchain-types/src/cip36/voting_pk.rs
  rust/cardano-blockchain-types/src/lib.rs
  rust/cardano-blockchain-types/src/utils/decode_helper.rs
  rust/cardano-blockchain-types/src/utils/mod.rs
Labels: enhancement
