Repository input-output-hk/catalyst-libs, pull requests merged in 2024-10, with the labels that each got.

#43 fix(rust/cardano-chain-follower): expose ciip509 mod
  rust/cardano-chain-follower/src/metadata/cip509/mod.rs
Labels: bug

#38 feat(general): Bumping `cat-ci` version to `v3.2.13`
  .gitignore
  .secret.template
  Earthfile
  docs/Earthfile
  rust/Earthfile
  rust/Justfile
  rust/c509-certificate/Earthfile
  rust/cbork/Earthfile
Labels: review me

#41 feat(rust/catalyst-voting): Tally procedure implementation
  .config/dictionaries/project.dic
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/crypto/elgamal.rs
  rust/catalyst-voting/src/crypto/group/babystep_giantstep.rs
  rust/catalyst-voting/src/crypto/group/mod.rs
  rust/catalyst-voting/src/crypto/group/ristretto255.rs
  rust/catalyst-voting/src/crypto/mod.rs
  rust/catalyst-voting/src/lib.rs
  rust/catalyst-voting/src/tally.rs
  rust/catalyst-voting/src/voter.rs
  rust/catalyst-voting/tests/voting_test.rs
Labels: review me

#44 ci(general): Add new workflow for allure report
  .github/workflows/generate-allure-report.yml
Labels: github_actions, review me

#39 fix(rust/c509-certificate): update docs
  docs/src/catalyst-standards/draft-cips/c509-plutus-restricted-certificate/c509-cert-plutus-restricted.cddl
  rust/c509-certificate/examples/cli/main.rs
  rust/c509-certificate/src/algorithm_identifier.rs
  rust/c509-certificate/src/attributes/attribute.rs
  rust/c509-certificate/src/attributes/mod.rs
  rust/c509-certificate/src/cert_tbs.rs
  rust/c509-certificate/src/extensions/mod.rs
  rust/c509-certificate/src/general_names/general_name.rs
  rust/c509-certificate/src/general_names/mod.rs
  rust/c509-certificate/src/issuer_sig_algo/mod.rs
  rust/c509-certificate/src/lib.rs
  rust/c509-certificate/src/name/mod.rs
  rust/c509-certificate/src/oid.rs
  rust/c509-certificate/src/subject_pub_key_algo/mod.rs
Labels: documentation, review me

#47 ci(general): Add test reporting to catalyst libs repo
  .github/workflows/generate-allure-report.yml
  rust/Earthfile
Labels: review me

#45 feat(rust/catalyst-voting): Tally proof generation and verification
  .config/dictionaries/project.dic
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/crypto/babystep_giantstep.rs
  rust/catalyst-voting/src/crypto/elgamal.rs
  rust/catalyst-voting/src/crypto/group/mod.rs
  rust/catalyst-voting/src/crypto/group/ristretto255.rs
  rust/catalyst-voting/src/crypto/hash.rs
  rust/catalyst-voting/src/crypto/mod.rs
  rust/catalyst-voting/src/crypto/zk_dl_equality.rs
  rust/catalyst-voting/src/lib.rs
  rust/catalyst-voting/src/tally/mod.rs
  rust/catalyst-voting/src/tally/proof.rs
  rust/catalyst-voting/tests/voting_test.rs
Labels: review me

#50 fix(rust/cardano-chain-follower): Update RBAC 509 API
  rust/cardano-chain-follower/src/metadata/cip509/mod.rs
  rust/cardano-chain-follower/src/metadata/cip509/rbac/role_data.rs
  rust/cardano-chain-follower/src/metadata/cip509/utils.rs
Labels: bug, review me

#22 feat(rust/c509-certificate): Update to version 11
  docs/src/catalyst-standards/draft-cips/c509-plutus-restricted-certificate/c509-cert-plutus-restricted.cddl
  rust/Justfile
  rust/c509-certificate/examples/cli/data/cert_sample_1.json
  rust/c509-certificate/examples/cli/main.rs
  rust/c509-certificate/examples/web/index.js
  rust/c509-certificate/src/algorithm_identifier.rs
  rust/c509-certificate/src/attributes/attribute.rs
  rust/c509-certificate/src/attributes/data.rs
  rust/c509-certificate/src/attributes/mod.rs
  rust/c509-certificate/src/big_uint.rs
  rust/c509-certificate/src/c509.rs
  rust/c509-certificate/src/cert_tbs.rs
  rust/c509-certificate/src/extensions/alt_name.rs
  rust/c509-certificate/src/extensions/extension/data.rs
  rust/c509-certificate/src/extensions/extension/mod.rs
  rust/c509-certificate/src/extensions/mod.rs
  rust/c509-certificate/src/general_names/data.rs
  rust/c509-certificate/src/general_names/general_name.rs
  rust/c509-certificate/src/general_names/mod.rs
  rust/c509-certificate/src/general_names/other_name_hw_module.rs
  rust/c509-certificate/src/helper/decode.rs
  rust/c509-certificate/src/helper/encode.rs
  rust/c509-certificate/src/helper/mod.rs
  rust/c509-certificate/src/issuer_sig_algo/data.rs
  rust/c509-certificate/src/issuer_sig_algo/mod.rs
  rust/c509-certificate/src/lib.rs
  rust/c509-certificate/src/name/mod.rs
  rust/c509-certificate/src/name/rdn.rs
  rust/c509-certificate/src/oid.rs
  rust/c509-certificate/src/subject_pub_key_algo/data.rs
  rust/c509-certificate/src/subject_pub_key_algo/mod.rs
  rust/c509-certificate/src/tbs_cert.rs
  rust/c509-certificate/src/time.rs
  rust/c509-certificate/src/wasm_binding.rs
  rust/cardano-chain-follower/Readme.md
Labels: enhancement

#49 fix(general): Bump Versions
  Earthfile
  docs/Earthfile
  integration_tests/rust/overhead_benchmark/Cargo.toml
  rust/Earthfile
  rust/c509-certificate/Cargo.toml
  rust/c509-certificate/Earthfile
  rust/c509-certificate/src/extensions/extension/data.rs
  rust/c509-certificate/src/extensions/extension/mod.rs
  rust/c509-certificate/src/lib.rs
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/src/metadata/cip509/mod.rs
  rust/cardano-chain-follower/src/metadata/cip509/rbac/role_data.rs
  rust/cardano-chain-follower/src/metadata/cip509/utils.rs
  rust/catalyst-voting/Cargo.toml
  rust/cbork-abnf-parser/Cargo.toml
  rust/cbork-cddl-parser/Cargo.toml
  rust/cbork/Cargo.toml
  rust/cbork/Earthfile
  rust/hermes-ipfs/Cargo.toml
  rust/hermes-ipfs/src/lib.rs
Labels: dependencies, review me

#54 feat(rust/catalyst-voting): Vote proof
  rust/catalyst-voting/src/crypto/babystep_giantstep.rs
  rust/catalyst-voting/src/crypto/elgamal.rs
  rust/catalyst-voting/src/crypto/group/ristretto255.rs
  rust/catalyst-voting/src/crypto/hash.rs
  rust/catalyst-voting/src/crypto/mod.rs
  rust/catalyst-voting/src/crypto/zk_dl_equality.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/challenges.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/polynomial.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/randomness_announcements.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/utils.rs
  rust/catalyst-voting/src/lib.rs
  rust/catalyst-voting/src/voter/mod.rs
  rust/catalyst-voting/src/voter/proof.rs
  rust/catalyst-voting/tests/voting_test.rs
Labels: review me

#56 fix(rust/cardano-chain-follower): Check condition for Block Roll Forward
  rust/cardano-chain-follower/examples/follow_chains.rs
  rust/cardano-chain-follower/src/follow.rs
Labels: bug, review me

#57 ci(general): Add coverage upload
  .config/dictionaries/project.dic
  .github/workflows/generate-allure-report.yml
  rust/Earthfile
Labels: review me

#58 feat(rust/catalyst-voting): Jormungandr transaction serde
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/crypto/babystep_giantstep.rs
  rust/catalyst-voting/src/crypto/elgamal/decoding.rs
  rust/catalyst-voting/src/crypto/elgamal/mod.rs
  rust/catalyst-voting/src/crypto/group/ristretto255/decoding.rs
  rust/catalyst-voting/src/crypto/group/ristretto255/mod.rs
  rust/catalyst-voting/src/crypto/mod.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/decoding.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/randomness_announcements.rs
  rust/catalyst-voting/src/lib.rs
  rust/catalyst-voting/src/txs/mod.rs
  rust/catalyst-voting/src/txs/v1/decoding.rs
  rust/catalyst-voting/src/txs/v1/mod.rs
  rust/catalyst-voting/src/utils.rs
  rust/catalyst-voting/src/vote_protocol/mod.rs
  rust/catalyst-voting/src/vote_protocol/tally/mod.rs
  rust/catalyst-voting/src/vote_protocol/tally/proof.rs
  rust/catalyst-voting/src/vote_protocol/voter/decoding.rs
  rust/catalyst-voting/src/vote_protocol/voter/mod.rs
  rust/catalyst-voting/src/vote_protocol/voter/proof.rs
  rust/catalyst-voting/tests/voting_test.rs
Labels: review me

#59 chore(rust/cardano-chain-follower): Bump crate version to 0.0.4
  rust/cardano-chain-follower/Cargo.toml
Labels: dependencies, review me

#60 feat(rust/catalyst-voting): Jormungandr tx building
  .config/dictionaries/project.dic
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/crypto/ed25519/decoding.rs
  rust/catalyst-voting/src/crypto/ed25519/mod.rs
  rust/catalyst-voting/src/crypto/elgamal/decoding.rs
  rust/catalyst-voting/src/crypto/elgamal/mod.rs
  rust/catalyst-voting/src/crypto/group/ristretto255/mod.rs
  rust/catalyst-voting/src/crypto/hash.rs
  rust/catalyst-voting/src/crypto/mod.rs
  rust/catalyst-voting/src/crypto/zk_dl_equality.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/challenges.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/decoding.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
  rust/catalyst-voting/src/lib.rs
  rust/catalyst-voting/src/txs/v1/decoding.rs
  rust/catalyst-voting/src/txs/v1/mod.rs
  rust/catalyst-voting/src/vote_protocol/committee.rs
  rust/catalyst-voting/src/vote_protocol/mod.rs
  rust/catalyst-voting/src/vote_protocol/tally/mod.rs
  rust/catalyst-voting/src/vote_protocol/tally/proof.rs
  rust/catalyst-voting/src/vote_protocol/voter/mod.rs
  rust/catalyst-voting/src/vote_protocol/voter/proof.rs
  rust/catalyst-voting/tests/voting_test.rs
Labels: review me

#61 fix(rust/catalyst-voting): Added missing feature flag, updated conversion from `CtOption` to `Option`
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/crypto/ed25519/decoding.rs
  rust/catalyst-voting/src/crypto/group/ristretto255/decoding.rs
  rust/catalyst-voting/src/txs/v1/mod.rs
  rust/catalyst-voting/src/vote_protocol/committee/decoding.rs
  rust/catalyst-voting/src/vote_protocol/committee/mod.rs
Labels: review me

#62 feat(docs): Moved catalyst-voting specific docs from the `catalyst-voices` repo
  .config/dictionaries/project.dic
  docs/src/architecture/08_concepts/catalyst_voting/.pages
  docs/src/architecture/08_concepts/catalyst_voting/crypto.md
  docs/src/architecture/08_concepts/catalyst_voting/transaction.md
  docs/src/architecture/08_concepts/catalyst_voting/tx_v1.abnf
  rust/catalyst-voting/src/crypto/group/mod.rs
  rust/catalyst-voting/src/crypto/zk_dl_equality.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/polynomial.rs
  rust/catalyst-voting/src/txs/v1/mod.rs
  rust/catalyst-voting/src/vote_protocol/mod.rs
  rust/catalyst-voting/src/vote_protocol/tally/mod.rs
  rust/catalyst-voting/src/vote_protocol/tally/proof.rs
  rust/catalyst-voting/src/vote_protocol/voter/mod.rs
  rust/catalyst-voting/src/vote_protocol/voter/proof.rs
Labels: review me

#66 feat(docs): Catalyst vote v2
  docs/src/architecture/08_concepts/catalyst_voting/crypto.md
  docs/src/architecture/08_concepts/catalyst_voting/transaction.md
  docs/src/architecture/08_concepts/catalyst_voting/tx_v2.cddl
  docs/src/architecture/08_concepts/catalyst_voting/tx_v2_cose_payload.cddl
Labels: review me

#70 docs(docs): Catalyst transaction v2
  docs/src/architecture/08_concepts/catalyst_voting/.pages
  docs/src/architecture/08_concepts/catalyst_voting/abnf/jorm.abnf
  docs/src/architecture/08_concepts/catalyst_voting/cat_v2.md
  docs/src/architecture/08_concepts/catalyst_voting/cddl/gen_vote_tx.cddl
  docs/src/architecture/08_concepts/catalyst_voting/cddl/gen_vote_tx_cose_payload.cddl
  docs/src/architecture/08_concepts/catalyst_voting/cddl/vote_tx_v2.cddl
  docs/src/architecture/08_concepts/catalyst_voting/gen_vote_tx.md
  docs/src/architecture/08_concepts/catalyst_voting/jorm.md
  docs/src/architecture/08_concepts/catalyst_voting/tx_v2.cddl
Labels: review me

#65 feat(rust/catalyst-voting): Vote protocol benchmarks
  rust/.cargo/config.toml
  rust/Earthfile
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/benches/vote_protocol.rs
  rust/catalyst-voting/src/crypto/zk_unit_vector/decoding.rs
  rust/catalyst-voting/src/txs/v1/decoding.rs
  rust/catalyst-voting/src/vote_protocol/tally/mod.rs
  rust/catalyst-voting/tests/voting_test.rs
  rust/deny.toml
Labels: review me

#71 feat(rust/catalyst-voting): Parallel iter usage for `fn encrypt_vote`
  rust/catalyst-voting/Cargo.toml
  rust/catalyst-voting/src/vote_protocol/voter/mod.rs
Labels: review me

#72 docs(docs): Move immutable ledger design docs from the `catalyst-voices` repo
  docs/src/architecture/08_concepts/immutable_ledger/.pages
  docs/src/architecture/08_concepts/immutable_ledger/cddl/block.cddl
  docs/src/architecture/08_concepts/immutable_ledger/cddl/genesis_to_prev_hash.cddl
  docs/src/architecture/08_concepts/immutable_ledger/images/ledger_schema.excalidraw
  docs/src/architecture/08_concepts/immutable_ledger/images/ledger_schema.svg
  docs/src/architecture/08_concepts/immutable_ledger/images/temporary_chain.excalidraw
  docs/src/architecture/08_concepts/immutable_ledger/images/temporary_chain.svg
  docs/src/architecture/08_concepts/immutable_ledger/ledger.md
Labels: review me

#73 feat(rust/catalyst-voting): Parallel iter usage for `fn generate_unit_vector_proof`
  rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
Labels: review me
