Repository input-output-hk/catalyst-libs, pull requests merged in 2025-02, with the labels that each got.

#192 feat(rust/catalyst-types): `uuid::Uuid` public import
  rust/catalyst-types/src/uuid/mod.rs
Labels: review me

#185 feat(rust/signed-doc): Add signing and verification logic to Catalyst Signed Docs
  rust/signed_doc/Cargo.toml
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/signature/mod.rs
Labels: enhancement

#193 fix(rust/signed-doc): Fix `ExtraFields::from_protected_header` error return
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
Labels: review me

#196 feat(rust/signed-doc): `CatalystSignedDocument` validator basic structure
  rust/signed_doc/src/doc_types/mod.rs
  rust/signed_doc/src/doc_types/proposal_document.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/document_id.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/document_type.rs
  rust/signed_doc/src/metadata/document_version.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/validator/mod.rs
Labels: review me

#194 feat(rust/signed-doc): Use Catalyst ID as KID
  rust/signed_doc/Cargo.toml
  rust/signed_doc/README.md
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/signature/mod.rs
Labels: enhancement

#198 fix(rust/signed-doc): Improving error message for `ContentType`
  rust/signed_doc/src/metadata/content_type.rs
Labels: review me

#199 feat(rust/signed-doc): Remove unneeded `uuid` dep, cleanup API
  rust/signed_doc/Cargo.toml
  rust/signed_doc/src/doc_types/mod.rs
  rust/signed_doc/src/doc_types/proposal_document.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/signature/mod.rs
Labels: review me

#202 feat(rust): Remove unneeded patch of `orx-pseudo-default`
  rust/Cargo.toml
Labels: review me

#200 feat(docs): Update Catalyst Signed Document specification.
  docs/src/architecture/08_concepts/catalyst_docs/comment.md
  docs/src/architecture/08_concepts/catalyst_docs/proposal.md
  docs/src/architecture/08_concepts/catalyst_docs/review.md
  docs/src/architecture/08_concepts/signed_doc/meta.md
Labels: review me

#211 feat(docs): Add defined list of ids for categories, proposal templates and comment templates
  docs/src/architecture/08_concepts/catalyst_docs/comment.md
  docs/src/architecture/08_concepts/catalyst_docs/proposal.md
Labels: review me

#210 feat(rust/rbac-registration): Use TransactionHash type
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/utils/test.rs
Labels: review me

#214 chore(general): Update catalyst-libs dependencies for chain follower and signed doc
  rust/cardano-chain-follower/Cargo.toml
  rust/signed_doc/Cargo.toml
Labels: review me

#217 feat(general): More types
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-blockchain-types/src/hashes.rs
  rust/cardano-blockchain-types/src/lib.rs
  rust/cardano-blockchain-types/src/network.rs
  rust/cardano-blockchain-types/src/stake_address.rs
  rust/cardano-chain-follower/Cargo.toml
  rust/catalyst-types/Cargo.toml
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/utils/test.rs
  rust/signed_doc/Cargo.toml
Labels: review me

#207 feat(rust/signed-doc): Comment and Proposal Document Validation
  rust/signed_doc/Cargo.toml
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/doc_types/mod.rs
  rust/signed_doc/src/doc_types/proposal_document.rs
  rust/signed_doc/src/error.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/algorithm.rs
  rust/signed_doc/src/metadata/content_encoding.rs
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/section.rs
  rust/signed_doc/src/metadata/utils.rs
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/src/utils/context.rs
  rust/signed_doc/src/utils/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/category.rs
  rust/signed_doc/src/validator/rules/content_encoding.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/section.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/src/validator/utils.rs
Labels: enhancement, review me

#219 feat(rust/signed-doc): Added unit tests for Catalyst Signed Docs validation rules
  rust/Earthfile
  rust/signed_doc/Cargo.toml
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/utils.rs
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/category.rs
  rust/signed_doc/src/validator/rules/content_encoding.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/section.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/src/validator/utils.rs
Labels: review me, do not merge yet

#221 fix(rust/catalyst-types): IdUri::is_id take self by reference
  rust/catalyst-types/src/id_uri/mod.rs
Labels: review me

#220 fix(rust/signed-doc): Minor fixes for `catalyst-singed-doc` crate
  rust/Earthfile
  rust/cardano-blockchain-types/src/txn_witness.rs
  rust/cardano-chain-follower/src/chain_sync_live_chains.rs
  rust/catalyst-types/Cargo.toml
  rust/catalyst-voting/Cargo.toml
  rust/signed_doc/Cargo.toml
  rust/signed_doc/README.md
  rust/signed_doc/bins/mk_signed_doc.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/utils.rs
Labels: review me

#224 feat(rust): Bump crates, get rid of the `fmmap 0.3.3` version
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-chain-follower/Cargo.toml
  rust/rbac-registration/Cargo.toml
  rust/signed_doc/Cargo.toml
Labels: review me

#225 fix(rust): Replace path with tag
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-chain-follower/Cargo.toml
  rust/rbac-registration/Cargo.toml
  rust/signed_doc/Cargo.toml
Labels: review me

#222 fix(general): coverage report
  .github/workflows/generate-allure-report.yml
Labels: review me
