Repository input-output-hk/catalyst-libs, pull requests merged in 2025-06, with the labels that each got.

#359 feat(rust/signed-doc): enum map representation for metadata
  rust/signed_doc/Cargo.toml
  rust/signed_doc/src/decode_context.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
Labels: enhancement, review me, requires architect review, backend

#355 fix(rust/signed-doc): Modify the `DocumentRef` structure
  rust/catalyst-types/src/uuid/uuid_v7.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/document_refs/doc_locator.rs
  rust/signed_doc/src/metadata/document_refs/doc_ref.rs
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/src/metadata/utils.rs
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/param_link_ref.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/section.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/src/validator/utils.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/signature.rs
  rust/signed_doc/tests/submission.rs
Labels: enhancement, review me, backend

#377 test(rust/signed-doc): Add a test case for invalid params and aliases in protected header
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#383 feat(rust/signed-doc): Catalyst Signed Documents `minicbor::Decode` impl
  rust/catalyst-types/src/catalyst_id/mod.rs
  rust/cbork-utils/src/deterministic_helper.rs
  rust/signed_doc/Cargo.toml
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/collaborators.rs
  rust/signed_doc/src/metadata/content_encoding.rs
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/metadata/doc_type.rs
  rust/signed_doc/src/metadata/document_refs/doc_locator.rs
  rust/signed_doc/src/metadata/document_refs/doc_ref.rs
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/section.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/src/metadata/utils.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/signature.rs
Labels: review me, squad: gatekeepers

#386 fix(rust/signed-doc): Fix an issue to using original bytes for signature verification.
  rust/signed_doc/bins/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/signature.rs
  rust/signed_doc/tests/submission.rs
Labels: review me, squad: gatekeepers

#390 fix(rust): Newest `nightly` `1.90` lint `mismatched_lifetime_syntaxes`
  rust/cardano-blockchain-types/src/multi_era_block_data.rs
Labels: review me

#389 test(rust/signed-doc): Add test cases for random kid, invalid COSE tag, and case-insensitive `content_encoding`
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#392 feat(rust/signed-doc): Add new `ContentType` variants: `Cddl` and `JsonSchema`
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/src/validator/rules/template.rs
Labels: review me, squad: gatekeepers
