Repository input-output-hk/catalyst-libs, pull requests merged in 2025-01, with the labels that each got.

#140 feat(rust): Add uniform problem report type
  .config/dictionaries/project.dic
  rust/Cargo.toml
  rust/Earthfile
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/lib.rs
  rust/catalyst-types/src/problem_report.rs
Labels: enhancement

#144 chore(general): update-forge-cli-to-1.5.1
  .github/workflows/ci.yml
  .github/workflows/generate-allure-report.yml
Labels: review me

#142 fix(rust/cardano-blockchain-types): implement new error report for CIP36
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-blockchain-types/src/metadata/cip36/key_registration.rs
  rust/cardano-blockchain-types/src/metadata/cip36/mod.rs
  rust/cardano-blockchain-types/src/metadata/cip36/registration_witness.rs
  rust/cardano-blockchain-types/src/metadata/cip36/validation.rs
Labels: review me

#147 fix(rust/catalyst-types): Add serde::Serialize to UUID types
  rust/catalyst-types/src/uuid/uuid_v4.rs
  rust/catalyst-types/src/uuid/uuid_v7.rs
Labels: enhancement

#115 fix(rust/cardano-chain-follower): Refactor chain follower to use `cardano-blockchain-types`
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/examples/follow_chains.rs
  rust/cardano-chain-follower/src/chain_sync.rs
  rust/cardano-chain-follower/src/chain_sync_config.rs
  rust/cardano-chain-follower/src/chain_sync_live_chains.rs
  rust/cardano-chain-follower/src/chain_sync_ready.rs
  rust/cardano-chain-follower/src/chain_update.rs
  rust/cardano-chain-follower/src/data/Readme.md
  rust/cardano-chain-follower/src/data/mainnet-genesis.vkey
  rust/cardano-chain-follower/src/data/preprod-genesis.vkey
  rust/cardano-chain-follower/src/data/preview-genesis.vkey
  rust/cardano-chain-follower/src/error.rs
  rust/cardano-chain-follower/src/follow.rs
  rust/cardano-chain-follower/src/lib.rs
  rust/cardano-chain-follower/src/metadata/cip36.rs
  rust/cardano-chain-follower/src/metadata/cip509.rs
  rust/cardano-chain-follower/src/metadata/mod.rs
  rust/cardano-chain-follower/src/metadata/raw_aux_data.rs
  rust/cardano-chain-follower/src/mithril_query.rs
  rust/cardano-chain-follower/src/mithril_snapshot.rs
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
  rust/cardano-chain-follower/src/mithril_snapshot_data.rs
  rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs
  rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
  rust/cardano-chain-follower/src/mithril_turbo_downloader.rs
  rust/cardano-chain-follower/src/multi_era_block_data.rs
  rust/cardano-chain-follower/src/network.rs
  rust/cardano-chain-follower/src/point.rs
  rust/cardano-chain-follower/src/snapshot_id.rs
  rust/cardano-chain-follower/src/stats/follower.rs
  rust/cardano-chain-follower/src/stats/live_chain.rs
  rust/cardano-chain-follower/src/stats/mithril.rs
  rust/cardano-chain-follower/src/stats/mod.rs
  rust/cardano-chain-follower/src/stats/rollback.rs
  rust/cardano-chain-follower/src/turbo_downloader/mod.rs
  rust/cardano-chain-follower/src/utils.rs
  rust/cardano-chain-follower/src/witness.rs
  rust/cardano-chain-follower/test_data/allegra.block
  rust/cardano-chain-follower/test_data/alonzo.block
  rust/cardano-chain-follower/test_data/babbage.block
  rust/cardano-chain-follower/test_data/byron.block
  rust/cardano-chain-follower/test_data/conway_tx_rbac/Readme.md
  rust/cardano-chain-follower/test_data/conway_tx_rbac/conway_1.block
  rust/cardano-chain-follower/test_data/conway_tx_rbac/conway_2.block
  rust/cardano-chain-follower/test_data/conway_tx_rbac/conway_3.block
  rust/cardano-chain-follower/test_data/mary.block
Labels: enhancement, review me

#151 fix(rust/cbork): Modify `decode_any` function
  rust/cbork-utils/Cargo.toml
  rust/cbork-utils/src/decode_helper.rs
Labels: review me

#101 feat(rust/signed-doc): Add deserializer for Catalyst Signed Documents
  .config/dictionaries/project.dic
  docs/src/architecture/08_concepts/rbac_kid_uri/.pages
  docs/src/architecture/08_concepts/rbac_kid_uri/kiduri.md
  rust/Earthfile
  rust/signed_doc/Cargo.toml
  rust/signed_doc/README.md
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/meta.schema.json
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/error.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/additional_fields.rs
  rust/signed_doc/src/metadata/content_encoding.rs
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/metadata/document_id.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/document_type.rs
  rust/signed_doc/src/metadata/document_version.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/signature/mod.rs
Labels: enhancement, review me, do not merge yet, F14

#153 fix(docs): Clarify the `ver` field meaning
  docs/src/architecture/08_concepts/signed_doc/spec.md
Labels: review me

#148 fix(rust/catalyst-types): Convert UUID types to cbor
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/uuid/mod.rs
  rust/catalyst-types/src/uuid/uuid_v4.rs
  rust/catalyst-types/src/uuid/uuid_v7.rs
Labels: enhancement, review me

#160 test(rust/rbac-registration): Fix test in CIP509
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134_uri_set.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/cardano/cip509/x509_chunks.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/test_data/cardano/conway_1.block
  rust/rbac-registration/src/test_data/cardano/conway_4.block
  rust/rbac-registration/src/utils/test.rs
Labels: enhancement

#165 feat(rust/cardano-blockchain-types): Add `Network` variants index
  rust/cardano-blockchain-types/src/network.rs
Labels: review me

#150 feat(rust/cardano-chain-follower): add thread and mmap file stats
  .config/dictionaries/project.dic
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/src/chain_sync.rs
  rust/cardano-chain-follower/src/chain_sync_config.rs
  rust/cardano-chain-follower/src/chain_sync_ready.rs
  rust/cardano-chain-follower/src/mithril_query.rs
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
  rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs
  rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
  rust/cardano-chain-follower/src/mithril_turbo_downloader.rs
  rust/cardano-chain-follower/src/stats/mod.rs
  rust/cardano-chain-follower/src/stats/thread/mod.rs
  rust/cardano-chain-follower/src/stats/thread/name.rs
  rust/cardano-chain-follower/src/turbo_downloader/mod.rs
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/lib.rs
  rust/catalyst-types/src/mmap_file.rs
Labels: enhancement, review me

#170 fix(rust/catalyst-types): Add validation during deserialising and instantiation of the `UuidV4`, `UuidV7`
  rust/catalyst-types/src/uuid/mod.rs
  rust/catalyst-types/src/uuid/uuid_v4.rs
  rust/catalyst-types/src/uuid/uuid_v7.rs
Labels: review me

#155 feat(rust/signed-doc): Serialize Signed Documents in CLI tool
  rust/signed_doc/Cargo.toml
  rust/signed_doc/README.md
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/algorithm.rs
  rust/signed_doc/src/metadata/content_encoding.rs
  rust/signed_doc/src/metadata/document_id.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/document_type.rs
  rust/signed_doc/src/metadata/document_version.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/signature/mod.rs
Labels: enhancement

#177 feat(rust/signed-doc): Improve `catalyst-signed-doc` crate API.
  rust/signed_doc/Cargo.toml
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
Labels: review me

#127 feat(rust/rbac-registration): refactoring
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/decode_context.rs
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs/c509.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs/c509_metadatum.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/certs/x509.rs
  rust/rbac-registration/src/cardano/cip509/rbac/metadata.rs
  rust/rbac-registration/src/cardano/cip509/rbac/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/pub_key.rs
  rust/rbac-registration/src/cardano/cip509/rbac/role_data.rs
  rust/rbac-registration/src/cardano/cip509/types/key_local_ref.rs
  rust/rbac-registration/src/cardano/cip509/types/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/payment_history.rs
  rust/rbac-registration/src/cardano/cip509/types/point_tx_idx.rs
  rust/rbac-registration/src/cardano/cip509/types/role_data.rs
  rust/rbac-registration/src/cardano/cip509/types/role_number.rs
  rust/rbac-registration/src/cardano/cip509/types/tx_input_hash.rs
  rust/rbac-registration/src/cardano/cip509/types/validation_signature.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134_uri_set.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip19.rs
  rust/rbac-registration/src/cardano/cip509/utils/mod.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/cardano/cip509/x509_chunks.rs
  rust/rbac-registration/src/cardano/mod.rs
  rust/rbac-registration/src/cardano/transaction/mod.rs
  rust/rbac-registration/src/cardano/transaction/raw_aux_data.rs
  rust/rbac-registration/src/cardano/transaction/witness.rs
  rust/rbac-registration/src/lib.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/point_tx_idx.rs
  rust/rbac-registration/src/registration/cardano/role_data.rs
  rust/rbac-registration/src/test_data/cardano/conway_1.block
  rust/rbac-registration/src/test_data/cardano/conway_4.block
  rust/rbac-registration/src/utils/decode_helper.rs
  rust/rbac-registration/src/utils/general.rs
  rust/rbac-registration/src/utils/hashing.rs
  rust/rbac-registration/src/utils/mod.rs
  rust/rbac-registration/src/utils/test.rs
Labels: review me

#176 fix(rust/signed-doc): Add `ProblemReport` to Catalyst sign document
  rust/signed_doc/Cargo.toml
  rust/signed_doc/examples/mk_signed_doc.rs
  rust/signed_doc/src/error.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/algorithm.rs
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/src/utils/context.rs
  rust/signed_doc/src/utils/mod.rs
Labels: enhancement, review me

#180 feat(rust/catalyst-types): Add report_duplicated_key and report_missing_keys functions to catalyst-types
  rust/catalyst-types/src/cbor_utils.rs
  rust/catalyst-types/src/lib.rs
  rust/cbork-utils/Cargo.toml
  rust/cbork-utils/src/decode_helper.rs
Labels: review me

#181 fix(rust/signed-doc): Change types for `brand_id`, `campaign_id` and `category_id` meta fields.
  docs/src/architecture/08_concepts/signed_doc/cddl/additional_meta.cddl
  docs/src/architecture/08_concepts/signed_doc/meta.md
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/extra_fields.rs
Labels: review me

#179 chore(general): Enable arithmetic_side_effects Clippy lint
  rust/Cargo.toml
  rust/Earthfile
  rust/c509-certificate/src/attributes/mod.rs
  rust/c509-certificate/src/extensions/extension/mod.rs
  rust/c509-certificate/src/extensions/mod.rs
  rust/c509-certificate/src/general_names/mod.rs
  rust/c509-certificate/src/name/mod.rs
  rust/cardano-blockchain-types/src/auxdata/scripts.rs
  rust/cardano-blockchain-types/src/fork.rs
  rust/cardano-blockchain-types/src/multi_era_block_data.rs
  rust/cardano-blockchain-types/src/network.rs
  rust/cardano-chain-follower/examples/follow_chains.rs
  rust/cardano-chain-follower/src/chain_sync.rs
  rust/cardano-chain-follower/src/chain_sync_live_chains.rs
  rust/cardano-chain-follower/src/follow.rs
  rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs
  rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
  rust/cardano-chain-follower/src/mithril_turbo_downloader.rs
  rust/cardano-chain-follower/src/stats/mod.rs
  rust/cardano-chain-follower/src/stats/rollback.rs
  rust/cardano-chain-follower/src/stats/thread/mod.rs
  rust/cardano-chain-follower/src/turbo_downloader/mod.rs
  rust/catalyst-types/src/cbor_utils.rs
  rust/catalyst-types/src/id_uri/mod.rs
  rust/catalyst-types/src/mmap_file.rs
  rust/catalyst-voting/src/lib.rs
  rust/clippy.toml
  rust/immutable-ledger/src/serialize.rs
  rust/vote-tx-v1/src/decoding.rs
Labels: review me
