Repository input-output-hk/catalyst-libs, pull requests merged in 2025-07, with the labels that each got.

#394 feat(rust/signed-doc): Add tests for minimal and full metadata fields
  rust/signed_doc/tests/decoding.rs
Labels: review me, backend, squad: gatekeepers

#400 feat(rust/signed-doc): Valid test cases for doc type and content fields
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#401 feat(rust/signed-doc): Added more decoding test cases, cleaned up `DecodeContext`
  rust/signed_doc/bins/mk_signed_doc.rs
  rust/signed_doc/src/decode_context.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/doc_type.rs
  rust/signed_doc/src/metadata/document_refs/doc_ref.rs
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers, rr: gatekeepers

#395 refactor(rust/signed-doc): Change `collabs` header to `collaborators`
  .config/dictionaries/project.dic
  rust/signed_doc/README.md
  rust/signed_doc/src/metadata/collaborators.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/signature.rs
Labels: review me, squad: gatekeepers

#402 feat(rust/signed-doc): Invalid test cases for protected headers
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#407 feat(rust/cbork): Add deterministically decoding array
  rust/cbork-utils/src/array.rs
  rust/cbork-utils/src/lib.rs
  rust/cbork-utils/src/map.rs
Labels: review me, squad: gatekeepers, rr: gatekeepers

#421 feat(rust/catalyst-types): Wrap Catalyst ID fields into Arc
  rust/catalyst-types/src/catalyst_id/mod.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
Labels: review me, squad: gatekeepers

#424 fix(general): Bumping catalyst-forge version
  .github/workflows/ci.yml
  .github/workflows/generate-allure-report.yml
Labels: review me

#423 feat(rust/signed-doc): Convenient trait implementations for `DocType`
  rust/signed_doc/src/metadata/doc_type.rs
Labels: review me, squad: gatekeepers

#426 feat(rust/signed-doc): Add a function to convert back `DocType` to deprecated UUID
  rust/signed_doc/src/metadata/doc_type.rs
Labels: review me, squad: gatekeepers

#434 feat(rust/signed-doc): Revert back to the original `DocType` format
  rust/catalyst-types/src/uuid/mod.rs
  rust/catalyst-types/src/uuid/uuid_v4.rs
  rust/catalyst-types/src/uuid/uuid_v7.rs
  rust/signed_doc/src/doc_types/mod.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/doc_type.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/submission.rs
Labels: review me, squad: gatekeepers

#441 feat(rust/signed-doc): Add a function to check deprecated version below v0.04 for a signed doc
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#422 chore(rust/hermes-ipfs): bump rust-ipfs for hermes-ipfs
  .config/dictionaries/project.dic
  integration_tests/rust/Cargo.toml
  rust/Cargo.toml
  rust/Earthfile
  rust/c509-certificate/Cargo.toml
  rust/c509-certificate/examples/cli/main.rs
  rust/c509-certificate/src/attributes/attribute.rs
  rust/c509-certificate/src/attributes/data.rs
  rust/c509-certificate/src/c509.rs
  rust/c509-certificate/src/extensions/extension/data.rs
  rust/c509-certificate/src/general_names/data.rs
  rust/c509-certificate/src/general_names/general_name.rs
  rust/c509-certificate/src/issuer_sig_algo/data.rs
  rust/c509-certificate/src/subject_pub_key_algo/data.rs
  rust/cardano-blockchain-types/src/auxdata/aux_data.rs
  rust/cardano-blockchain-types/src/auxdata/block.rs
  rust/cardano-blockchain-types/src/metadata/cip36/validation.rs
  rust/cardano-blockchain-types/src/txn_witness.rs
  rust/cardano-chain-follower/src/chain_sync.rs
  rust/cardano-chain-follower/src/chain_sync_live_chains.rs
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
  rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs
  rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
  rust/cardano-chain-follower/src/mithril_turbo_downloader.rs
  rust/cardano-chain-follower/src/snapshot_id.rs
  rust/cardano-chain-follower/src/turbo_downloader/mod.rs
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/catalyst_id/mod.rs
  rust/catalyst-types/src/mmap_file.rs
  rust/deny.toml
  rust/hermes-ipfs/Cargo.toml
  rust/hermes-ipfs/examples/add-file-with-pinning.rs
  rust/hermes-ipfs/src/lib.rs
  rust/immutable-ledger/src/serialize.rs
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134_uri_set.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rust-toolchain.toml
  rust/signed_doc/bins/mk_signed_doc.rs
  rust/signed_doc/src/metadata/extra_fields.rs
Labels: dependencies, backend

#444 fix(rust/rbac-registration): `CatalystId` wrong `subnet` value for mainnet network
  rust/cardano-chain-follower/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/validation.rs
Labels: review me

#338 feat(rust/signed-doc): Implement new Catalyst Signed Doc
  .config/dictionaries/project.dic
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-chain-follower/Cargo.toml
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/catalyst_id/mod.rs
  rust/catalyst-types/src/uuid/mod.rs
  rust/catalyst-types/src/uuid/uuid_v4.rs
  rust/catalyst-types/src/uuid/uuid_v7.rs
  rust/cbork-utils/src/array.rs
  rust/cbork-utils/src/decode_context.rs
  rust/cbork-utils/src/decode_helper.rs
  rust/cbork-utils/src/deterministic_helper.rs
  rust/cbork-utils/src/lib.rs
  rust/cbork-utils/src/map.rs
  rust/cbork-utils/src/with_cbor_bytes.rs
  rust/rbac-registration/Cargo.toml
  rust/signed_doc/Cargo.toml
  rust/signed_doc/README.md
  rust/signed_doc/bins/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/decode_context.rs
  rust/signed_doc/src/doc_types/mod.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/collaborators.rs
  rust/signed_doc/src/metadata/content_encoding.rs
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/metadata/doc_type.rs
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/metadata/document_refs/doc_locator.rs
  rust/signed_doc/src/metadata/document_refs/doc_ref.rs
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/section.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/src/metadata/utils.rs
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/content_encoding.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/param_link_ref.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/section.rs
  rust/signed_doc/src/validator/rules/signature_kid.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/src/validator/utils.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/signature.rs
  rust/signed_doc/tests/submission.rs
Labels: do not merge yet

#449 feat(general): `catalyst-types` version `0.0.5`
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-chain-follower/Cargo.toml
  rust/catalyst-types/Cargo.toml
  rust/rbac-registration/Cargo.toml
  rust/signed_doc/Cargo.toml
Labels: review me
