Repository input-output-hk/catalyst-libs, pull requests merged in 2025-05, with the labels that each got.

#298 feat(rust/signed-doc): Document's content static schema validation rule
  Earthfile
  rust/Earthfile
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/signature.rs
  rust/signed_doc/tests/submission.rs
  specs/signed_docs/docs/payload_schemas/proposal_submission_action.schema.json
Labels: review me

#301 chore(deps): bump input-output-hk/catalyst-forge/actions/* from 1.7.1 to 1.7.2
  .github/workflows/ci.yml
  .github/workflows/generate-allure-report.yml
Labels: github_actions

#306 fix(rust/cardano-chain-follower): Fix `cardano-chain-follower` build
  rust/cardano-chain-follower/Cargo.toml
Labels: review me

#283 feat(rust/catalyst-types): change RoleIndex to enum
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/id_uri/errors.rs
  rust/catalyst-types/src/id_uri/mod.rs
  rust/catalyst-types/src/id_uri/role_index.rs
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/rbac/metadata.rs
  rust/rbac-registration/src/cardano/cip509/rbac/role_data.rs
  rust/rbac-registration/src/cardano/cip509/types/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/role_data.rs
  rust/rbac-registration/src/cardano/cip509/types/role_number.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/update_rbac.rs
  rust/rbac-registration/src/utils/test.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/signature_kid.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/signature.rs
  rust/signed_doc/tests/submission.rs
Labels: review me, do not merge yet

#313 fix(rust): Update Mithril Crate Dependency
  rust/cardano-chain-follower/Cargo.toml
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
  rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
  rust/cardano-chain-follower/src/mithril_turbo_downloader.rs
Labels: review me

#312 fix(rust/rbac-registration): Validate validation_signature with the latest signing public key of Role 0
  rust/catalyst-types/src/conversion.rs
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/types/validation_signature.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/utils/test.rs
Labels: bug, F14-RC2

#310 feat(rust/rbac-registration): refactor cip509 extract key fns
  rust/rbac-registration/src/cardano/cip509/utils/extract_key.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
Labels: enhancement, review me

#319 fix(rust/signed-doc): Catalyst Signed Document missing signature check
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/tests/signature.rs
Labels: review me

#325 fix(docs): correct python type annotations in documentation generator
  .vscode/settings.recommended.json
  docs/src/architecture/08_concepts/signed_doc/diagrams/all.dot
  specs/gen_docs/gen/doc_generator.py
  specs/gen_docs/gen/doc_relationship_diagrams.py
  specs/gen_docs/gen/graphviz_doc_diagram.py
  specs/gen_docs/spec/document.py
  specs/gen_docs/spec/signed_doc.py
Labels: review me, requires architect review

#326 docs(docs): Better define the document encoding restrictions.
  docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/decision_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_template.md
  docs/src/architecture/08_concepts/signed_doc/metadata.md
  docs/src/architecture/08_concepts/signed_doc/spec.md
  docs/src/architecture/08_concepts/signed_doc/types.md
  specs/gen_docs/gen/spec_md.py
  specs/signed_doc.json
  specs/signed_docs/authors_copyright.cue
  specs/signed_docs/documentation_links.cue
Labels: documentation, review me

#314 feat(rust/rbac-registration): Update RBAC examples according to the latest channges
  rust/rbac-registration/examples.md
Labels: documentation, review me

#317 refactor(rust/signed-doc): add parameters field
  rust/signed_doc/src/metadata/extra_fields.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/category.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me

#337 fix(rust/signed-doc): `ParametersRule` impl
  rust/signed_doc/src/validator/rules/parameters.rs
Labels: review me

#342 feat(docs): Add payload examples
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  specs/gen_docs/gen/docs_page_md.py
  specs/gen_docs/pyproject.toml
  specs/gen_docs/spec/payload.py
  specs/gen_docs/uv.lock
  specs/signed_doc.json
  specs/signed_docs/docs/payload_schemas/proposal_submission_action.draft.example.json
  specs/signed_docs/docs/payload_schemas/proposal_submission_action.final.example.json
  specs/signed_docs/docs/payload_schemas/proposal_submission_action.hide.example.json
  specs/signed_docs/docs/proposal_submission_action.cue
  specs/signed_docs/payload.cue
Labels: review me, requires architect review

#345 fix(rust/signed-doc): Preserve original `raw_bytes`
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/tests/decoding.rs
Labels: bug, review me

#347 fix(rust/signed-doc): Apply new `DocType`
  rust/catalyst-types/src/uuid/mod.rs
  rust/catalyst-types/src/uuid/uuid_v4.rs
  rust/catalyst-types/src/uuid/uuid_v7.rs
  rust/signed_doc/src/doc_types/mod.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/doc_type.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/submission.rs
Labels: enhancement, review me

#350 fix(rust/signed-doc): Correct CBOR content type and data validation
  rust/signed_doc/Cargo.toml
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/validator/rules/content_type.rs
Labels: bug, review me
