Repository input-output-hk/catalyst-libs, pull requests merged in 2025-03, with the labels that each got.

#228 feat(rust): `RegistrationChain` additional validation, added `From<TxnIndex> for u16`
  rust/cardano-blockchain-types/Cargo.toml
  rust/cardano-blockchain-types/src/txn_index.rs
  rust/cardano-chain-follower/Cargo.toml
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/signed_doc/Cargo.toml
Labels: review me

#230 feat(rust/cardano-blockchain-types): Implement (derive) Debug for Cip36
  rust/cardano-blockchain-types/src/metadata/cip36/mod.rs
  rust/cardano-chain-follower/src/chain_sync.rs
Labels: review me

#231 feat(rust/cardano-blockchain-types): Fix comments
  rust/cardano-blockchain-types/src/metadata/cip36/key_registration.rs
Labels: review me

#239 chore(general): Run CI when PR is opened
  .github/workflows/ci.yml
Labels: review me

#236 fix(rust/rbac-registration): RBAC reg chain with historical data
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/point_data.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
Labels: enhancement, review me, F14

#237 feat(rust/signed-doc): Update `CatalystSignedDocument` decoding/encoding
  rust/signed_doc/src/lib.rs
Labels: review me

#229 test(rust/signed-doc): Add integration test validating all functionalities against the spec
  rust/catalyst-types/src/id_uri/mod.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/providers.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/decoding.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/signature.rs
Labels: review me

#251 fix(rust/rbac-registration): Implement (derive) Copy for LocalRefInt and KeyLocalRef
  rust/rbac-registration/src/cardano/cip509/types/key_local_ref.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
Labels: review me

#250 chore(rust/cardano-chain-follower): Cleanup updating follower state after getting a new update
  rust/cardano-chain-follower/src/follow.rs
  rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs
Labels: review me

#245 fix(rust/cardano-chain-follower): fix immutable roll forward events
  rust/Justfile
  rust/cardano-chain-follower/examples/follow_chains.rs
  rust/cardano-chain-follower/src/chain_sync.rs
  rust/cardano-chain-follower/src/follow.rs
  rust/cardano-chain-follower/src/mithril_snapshot.rs
  rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs
  rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
Labels: review me

#257 feat(rust/signed-doc): Validation and tests for submission action
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/tests/submission.rs
Labels: F14

#244 feat(rust/rbac-registration): Record each role data fields
  rust/rbac-registration/Cargo.toml
  rust/rbac-registration/src/cardano/cip509/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/cert_or_pk.rs
  rust/rbac-registration/src/cardano/cip509/types/mod.rs
  rust/rbac-registration/src/cardano/cip509/types/role_data_record.rs
  rust/rbac-registration/src/cardano/cip509/utils/extract_key.rs
  rust/rbac-registration/src/cardano/cip509/utils/mod.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
  rust/rbac-registration/src/registration/cardano/update_rbac.rs
Labels: enhancement, review me, F14

#258 fix(rust/cardano-chain-follower): Fix mithril snapshot validation
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
Labels: review me

#259 fix(rust/rbac-registration): Pass the (sub)net parameter to IdUri constructor
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
Labels: bug
