Repository input-output-hk/catalyst-libs, pull requests merged in 2025-04, with the labels that each got.

#267 feat(rust/rbac-registration): Add `Clone` to `RegistrationChain`
  rust/rbac-registration/src/registration/cardano/mod.rs
Labels: review me

#266 fix(rust/signed-doc): Update the Catalyst Signed Document time based validation
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/submission.rs
Labels: review me

#269 fix(rust): Fixing rust build
  rust/catalyst-types/Cargo.toml
Labels: review me

#272 fix(docs): Validation of docs generation in CI
  .config/dictionaries/project.dic
  docs/Earthfile
  docs/src/architecture/08_concepts/signed_doc/doc_relationships.d2
  docs/src/architecture/08_concepts/signed_doc/doc_relationships.svg
  docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/election_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_template.md
  docs/src/architecture/08_concepts/signed_doc/metadata.md
  docs/src/architecture/08_concepts/signed_doc/spec.md
  docs/src/architecture/08_concepts/signed_doc/types.md
  specs/Earthfile
  specs/Justfile
  specs/gen_docs/common.py
  specs/gen_docs/gen_docs_page_md.py
  specs/gen_docs/gen_metadata_md.py
  specs/gen_docs/gen_types_md.py
  specs/gen_docs/generate_docs.py
  specs/generic/date.cue
  specs/signed_doc.json
  specs/signed_docs/authors_copyright.cue
  specs/signed_docs/docs/all.cue
  specs/signed_docs/docs/brand_parameters.cue
  specs/signed_docs/docs/campaign_parameters.cue
  specs/signed_docs/docs/category_parameters.cue
  specs/signed_docs/docs/comment_action.cue
  specs/signed_docs/docs/comment_moderation_action.cue
  specs/signed_docs/docs/election_parameters.cue
  specs/signed_docs/docs/proposal.cue
  specs/signed_docs/docs/proposal_comment.cue
  specs/signed_docs/docs/proposal_comment_meta_template.cue
  specs/signed_docs/docs/proposal_comment_template.cue
  specs/signed_docs/docs/proposal_meta_template.cue
  specs/signed_docs/docs/proposal_moderation_action.cue
  specs/signed_docs/docs/proposal_submission_action.cue
  specs/signed_docs/docs/proposal_template.cue
  specs/signed_docs/signed_doc.cue
Labels: review me, requires architect review

#273 fix(docs): Add document references to all currently specified documents
  docs/src/architecture/08_concepts/signed_doc/doc_relationships.d2
  docs/src/architecture/08_concepts/signed_doc/doc_relationships.svg
  docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/election_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_template.md
  docs/src/architecture/08_concepts/signed_doc/metadata.md
  specs/gen_docs/common.py
  specs/gen_docs/gen_docs_relationship_diagram_d2.py
  specs/gen_docs/generate_docs.py
  specs/signed_doc.json
  specs/signed_docs/docs/brand_parameters.cue
  specs/signed_docs/docs/campaign_parameters.cue
  specs/signed_docs/docs/category_parameters.cue
  specs/signed_docs/docs/comment_moderation_action.cue
  specs/signed_docs/docs/election_parameters.cue
  specs/signed_docs/docs/proposal.cue
  specs/signed_docs/docs/proposal_comment.cue
  specs/signed_docs/docs/proposal_comment_template.cue
  specs/signed_docs/docs/proposal_moderation_action.cue
  specs/signed_docs/docs/proposal_template.cue
  specs/signed_docs/metadata.cue
Labels: review me

#271 fix(rust/signed-doc): Update DocumentRef to require version field
  rust/signed_doc/src/metadata/document_ref.rs
  rust/signed_doc/src/validator/rules/category.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/submission.rs
Labels: review me, F14

#279 feat(rust/signed-doc): `mk_signed_doc` cli tool to accept bip32 extended private keys
  rust/signed_doc/Cargo.toml
  rust/signed_doc/bins/mk_signed_doc.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/validator/rules/signature_kid.rs
  rust/signed_doc/tests/common/mod.rs
  rust/signed_doc/tests/signature.rs
Labels: review me

#282 feat(rust/signed-doc): `SignatureKidRule` improve report message
  rust/signed_doc/src/validator/rules/signature_kid.rs
Labels: review me

#280 feat(rust/rbac-registration): Certificate self-signed validation
  rust/c509-certificate/src/cert_tbs.rs
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
Labels: enhancement, review me, F14

#284 fix(docs): Updated TODO place holder text with context
  docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/election_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_meta_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_template.md
  specs/gen_docs/gen_docs_page_md.py
Labels: documentation, do not merge yet

#285 feat(docs): Add more doc definitions/specifications
  docs/src/architecture/08_concepts/signed_doc/doc_relationships.d2
  docs/src/architecture/08_concepts/signed_doc/doc_relationships.svg
  docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  docs/src/architecture/08_concepts/signed_doc/metadata.md
  specs/gen_docs/common.py
  specs/gen_docs/gen_metadata_md.py
  specs/signed_doc.json
  specs/signed_docs/cddl_defs.cue
  specs/signed_docs/docs/comment_action.cue
  specs/signed_docs/docs/proposal.cue
  specs/signed_docs/docs/proposal_comment.cue
  specs/signed_docs/docs/proposal_submission_action.cue
  specs/signed_docs/documentation_links.cue
  specs/signed_docs/metadata.cue
Labels: review me, requires architect review

#291 fix(rust/cardano-chain-follower): Fixing `ProtectedLiveChainBlockList::get_block` method, correctly process fuzzy point
  rust/cardano-chain-follower/src/chain_sync_live_chains.rs
Labels: review me, do not merge yet

#295 fix(rust/cardano-chain-follower): `webpki-roots` crate release breaking change
  rust/cardano-chain-follower/Cargo.toml
Labels: review me

#296 feat(rust): Revert locking `webpki-roots`, update `cat-ci`
  Earthfile
  docs/Earthfile
  docs/src/architecture/08_concepts/catalyst_voting/cddl/Earthfile
  docs/src/architecture/08_concepts/immutable_ledger/cddl/Earthfile
  docs/src/architecture/08_concepts/signed_doc/cddl/Earthfile
  rust/Earthfile
  rust/c509-certificate/Earthfile
  rust/cardano-chain-follower/Cargo.toml
  rust/deny.toml
  specs/Earthfile
  utilities/docs-preview/Earthfile
Labels: review me
