Repository input-output-hk/catalyst-libs, pull requests merged in 2025-09, with the labels that each got.

#503 feat(rust/signed-doc): Initial `catalyst_signed_documents_rules!` macro implementation
  rust/catalyst-signed-doc-macro/src/lib.rs
  rust/catalyst-signed-doc-macro/src/rules/mod.rs
  rust/catalyst-signed-doc-macro/src/types_consts.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/content.rs
  rust/signed_doc/src/validator/rules/content_encoding.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/id.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/section.rs
  rust/signed_doc/src/validator/rules/signature_kid.rs
  rust/signed_doc/src/validator/rules/ver.rs
Labels: review me, squad: gatekeepers

#517 chore(general): bump cat-ci versions to `v3.5.12`
  Earthfile
  docs/Earthfile
  docs/src/architecture/08_concepts/catalyst_voting/cddl/Earthfile
  docs/src/architecture/08_concepts/immutable_ledger/cddl/Earthfile
  docs/src/architecture/08_concepts/signed_doc/cddl/Earthfile
  rust/Earthfile
  rust/c509-certificate/Earthfile
  specs/Earthfile
  specs/generators/pages/signed_doc/cddl/Earthfile.jinja
  utilities/docs-preview/Earthfile
Labels: review me

#519 feat(rust/signed-doc): Add validation rule to check authors of new doc version match previous those in version.
  rust/catalyst-signed-doc-macro/src/rules/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/original_author.rs
Labels: review me, squad: gatekeepers

#507 fix(rust/rbac-registration): Validate witness for stake address and payment address URIs in certificate
  rust/rbac-registration/src/cardano/cip509/cip509.rs
  rust/rbac-registration/src/cardano/cip509/utils/cip134_uri_set.rs
  rust/rbac-registration/src/cardano/cip509/validation.rs
  rust/rbac-registration/src/registration/cardano/mod.rs
Labels: backend, fyi: hermetics, fyi: gatekeepers

#532 feat(rust/signed-doc): Add `NotSpecified` to `ContentTypeRule`
  rust/catalyst-signed-doc-macro/src/rules/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/content_type.rs
Labels: review me, squad: gatekeepers

#534 feat(rust/signed-doc): Not required `content-type` during decoding
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/validator/rules/content.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#540 feat(rust/signed-doc): Split into two `ContentRule` and `TemplateRule`
  rust/catalyst-signed-doc-macro/src/rules/mod.rs
  rust/signed_doc/src/builder.rs
  rust/signed_doc/src/content.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/signature/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/content.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/src/validator/rules/utils.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#536 fix(docs): Catalyst Signed Document specification fixes
  docs/src/architecture/08_concepts/signed_doc/diagrams/all.dot
  docs/src/architecture/08_concepts/signed_doc/diagrams/all.dot.svg
  docs/src/architecture/08_concepts/signed_doc/diagrams/contest_delegation.dot
  docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/category_parameters_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/contest_delegation.md
  docs/src/architecture/08_concepts/signed_doc/docs/contest_parameters.md
  docs/src/architecture/08_concepts/signed_doc/docs/contest_parameters_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/presentation_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
  docs/src/architecture/08_concepts/signed_doc/docs/rep_nomination.md
  docs/src/architecture/08_concepts/signed_doc/docs/rep_nomination_form_template.md
  docs/src/architecture/08_concepts/signed_doc/docs/rep_profile.md
  docs/src/architecture/08_concepts/signed_doc/docs/rep_profile_form_template.md
  docs/src/architecture/08_concepts/signed_doc/metadata.md
  docs/src/architecture/08_concepts/signed_doc/spec.md
  docs/src/architecture/08_concepts/signed_doc/types.md
  specs/Earthfile
  specs/definitions/generic/optional.cue
  specs/definitions/signed_docs/authors_copyright.cue
  specs/definitions/signed_docs/cose_headers.cue
  specs/definitions/signed_docs/docs/comment_moderation_action.cue
  specs/definitions/signed_docs/docs/contest_delegation.cue
  specs/definitions/signed_docs/docs/proposal_moderation_action.cue
  specs/definitions/signed_docs/payload.cue
  specs/definitions/signed_docs/signed_doc.cue
  specs/generators/packages/spec/src/spec/document.py
  specs/generators/packages/spec/src/spec/payload.py
  specs/generators/pages/signed_doc/docs/document_page.md.jinja
  specs/generators/src/docs/doc_generator.py
  specs/generators/src/docs/docs_page_md.py
  specs/signed_doc.json
Labels: review me, requires architect review, squad: gatekeepers

#558 chore(rust/rbac-registration): Release v0.0.10
  rust/rbac-registration/Cargo.toml
Labels: review me, squad: gatekeepers

#565 feat(rust/catalyst-types): Admin roles for the `RoleId` enum
  rust/catalyst-types/Cargo.toml
  rust/catalyst-types/src/catalyst_id/role_index.rs
Labels: review me, squad: gatekeepers

#569 feat(rust/signed-doc): Add `chain` metadata field in the Signed Doc header
  rust/cardano-chain-follower/examples/follow_chains.rs
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
  rust/catalyst-types/src/catalyst_id/role_index.rs
  rust/hermes-ipfs/examples/pubsub.rs
  rust/signed_doc/src/lib.rs
  rust/signed_doc/src/metadata/chain.rs
  rust/signed_doc/src/metadata/document_refs/doc_locator.rs
  rust/signed_doc/src/metadata/document_refs/doc_ref.rs
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/metadata/mod.rs
  rust/signed_doc/src/metadata/supported_field.rs
  rust/signed_doc/tests/decoding.rs
Labels: review me, squad: gatekeepers

#567 feat(rust/signed-doc): implement DocumentOwnershipRule
  rust/Earthfile
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/original_author.rs
  rust/signed_doc/src/validator/rules/ownership/mod.rs
  rust/signed_doc/src/validator/rules/ownership/tests.rs
Labels: review me, squad: gatekeepers

#574 feat(rust/signed-doc): Signed Document validation rules change
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/section.rs
Labels: review me, squad: gatekeepers
