Repository input-output-hk/catalyst-libs, pull requests merged in 2025-08, with the labels that each got.

#462 ci(general): add project fields validation
  .github/workflows/validate-project-fields.yml
Labels: review me

#468 chore(rust/cardano-chain-follower): Bump `cardano-chain-follower` version
  rust/cardano-chain-follower/Cargo.toml
Labels: review me

#475 feat(rust/signed-doc): Add more supporting media types
  rust/signed_doc/Cargo.toml
  rust/signed_doc/src/metadata/content_type.rs
  rust/signed_doc/src/validator/rules/content_type.rs
  rust/signed_doc/src/validator/rules/template.rs
Labels: review me, squad: gatekeepers

#484 fix(rust/cardano-chain-follower): Fix `cardano-chain-follower` compilation issues, because of the latest `cardano-blockchain-types` crate.
  rust/cardano-chain-follower/src/chain_sync.rs
  rust/cardano-chain-follower/src/chain_sync_config.rs
  rust/cardano-chain-follower/src/chain_sync_live_chains.rs
  rust/cardano-chain-follower/src/chain_sync_ready.rs
  rust/cardano-chain-follower/src/error.rs
  rust/cardano-chain-follower/src/mithril_snapshot_config.rs
  rust/cardano-chain-follower/src/stats/mod.rs
  rust/cardano-chain-follower/src/stats/rollback.rs
Labels: review me, backend, squad: gatekeepers, squad: hermetics

#486 fix(rust/signed-doc): `parameters` linked referenced document validation
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/param_link_ref.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/tests/comment.rs
Labels: review me, squad: gatekeepers

#494 fix(rust/cardano-chain-follower): Fixing occurred deadlock after starting using `DashMap::entry` instead of `DashMap::get` method
  rust/cardano-chain-follower/src/chain_sync_ready.rs
  rust/cardano-chain-follower/src/lib.rs
  rust/cardano-chain-follower/src/stats/mod.rs
  rust/cardano-chain-follower/src/stats/rollback.rs
Labels: review me, squad: gatekeepers

#496 chore(rust/signed-doc): Proper `DocumentRefs` functional validation
  rust/signed_doc/src/metadata/document_refs/mod.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/doc_ref.rs
  rust/signed_doc/src/validator/rules/parameters.rs
  rust/signed_doc/src/validator/rules/reply.rs
  rust/signed_doc/src/validator/rules/template.rs
  rust/signed_doc/src/validator/utils.rs
Labels: review me, squad: gatekeepers

#497 refactor(rust/signed-doc): Move `validate_id_and_ver` as separate rules `IdRule` and `VerRule`
  rust/signed_doc/src/providers.rs
  rust/signed_doc/src/validator/mod.rs
  rust/signed_doc/src/validator/rules/id.rs
  rust/signed_doc/src/validator/rules/mod.rs
  rust/signed_doc/src/validator/rules/ver.rs
  rust/signed_doc/tests/comment.rs
  rust/signed_doc/tests/proposal.rs
  rust/signed_doc/tests/submission.rs
Labels: review me, squad: gatekeepers
